INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '스팸 / 도배', '반복적인 광고 게시물', '처리완료', 43);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (1, 41);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '반복적인 광고 게시물', '허위신고', 38);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (2, 66);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '스팸 / 도배', '반복적인 광고 게시물', '보류', 97);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (3, 9);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '허위정보', '욕설 및 비방 포함', '처리완료', 100);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (4, 1);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '욕설 및 비방 포함', '허위신고', 21);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (5, 34);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '스팸 / 도배', '저작권 침해 신고', '보류', 70);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (6, 11);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '스팸 / 도배', '잘못된 정보 포함', '처리중', 15);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (7, 91);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '잘못된 정보 포함', '처리완료', 34);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (8, 96);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '권리 침해', '욕설 및 비방 포함', '처리중', 38);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (9, 82);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '권리 침해', '반복적인 광고 게시물', '처리완료', 46);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (10, 75);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '부적절한 내용', '잘못된 정보 포함', '처리완료', 31);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (11, 78);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '스팸 / 도배', '기타 문제 신고', '허위신고', 51);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (12, 69);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '부적절한 내용', '반복적인 광고 게시물', '보류', 22);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (13, 42);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '권리 침해', '기타 문제 신고', '허위신고', 97);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (14, 76);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '권리 침해', '반복적인 광고 게시물', '처리중', 36);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (15, 40);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '반복적인 광고 게시물', '보류', 96);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (16, 67);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '욕설 및 비방 포함', '허위신고', 29);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (17, 19);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '허위정보', '기타 문제 신고', '보류', 65);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (18, 84);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '반복적인 광고 게시물', '보류', 46);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (19, 82);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '허위정보', '욕설 및 비방 포함', '처리완료', 16);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (20, 92);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '허위정보', '기타 문제 신고', '처리완료', 26);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (21, 11);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '부적절한 내용', '저작권 침해 신고', '처리중', 98);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (22, 75);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '저작권 침해 신고', '허위신고', 2);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (23, 23);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '부적절한 내용', '저작권 침해 신고', '처리중', 3);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (24, 56);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '허위정보', '잘못된 정보 포함', '처리중', 56);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (25, 43);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '허위정보', '반복적인 광고 게시물', '보류', 81);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (26, 42);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '권리 침해', '욕설 및 비방 포함', '처리완료', 78);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (27, 93);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '부적절한 내용', '기타 문제 신고', '처리중', 84);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (28, 58);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '욕설 및 비방 포함', '보류', 100);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (29, 33);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '잘못된 정보 포함', '처리중', 70);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (30, 92);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '스팸 / 도배', '기타 문제 신고', '처리중', 47);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (31, 99);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '스팸 / 도배', '반복적인 광고 게시물', '처리완료', 32);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (32, 85);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '부적절한 내용', '잘못된 정보 포함', '처리중', 93);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (33, 22);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '저작권 침해 신고', '보류', 63);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (34, 13);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '권리 침해', '반복적인 광고 게시물', '처리완료', 38);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (35, 94);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '반복적인 광고 게시물', '처리완료', 29);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (36, 35);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '저작권 침해 신고', '보류', 9);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (37, 11);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '권리 침해', '기타 문제 신고', '보류', 84);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (38, 22);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '부적절한 내용', '욕설 및 비방 포함', '보류', 20);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (39, 27);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '스팸 / 도배', '반복적인 광고 게시물', '허위신고', 77);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (40, 11);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '기타 문제 신고', '처리완료', 54);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (41, 63);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '스팸 / 도배', '잘못된 정보 포함', '처리완료', 58);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (42, 13);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '부적절한 내용', '기타 문제 신고', '허위신고', 58);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (43, 10);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '부적절한 내용', '기타 문제 신고', '처리완료', 93);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (44, 81);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '권리 침해', '욕설 및 비방 포함', '처리중', 82);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (45, 17);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '허위정보', '잘못된 정보 포함', '처리완료', 20);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (46, 48);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '부적절한 내용', '잘못된 정보 포함', '처리완료', 98);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (47, 63);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '부적절한 내용', '반복적인 광고 게시물', '처리중', 54);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (48, 95);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '권리 침해', '기타 문제 신고', '처리완료', 59);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (49, 77);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '스팸 / 도배', '잘못된 정보 포함', '보류', 41);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (50, 58);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '부적절한 내용', '잘못된 정보 포함', '처리중', 5);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (51, 63);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '허위정보', '잘못된 정보 포함', '처리중', 56);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (52, 88);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '스팸 / 도배', '기타 문제 신고', '허위신고', 100);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (53, 47);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '반복적인 광고 게시물', '처리완료', 96);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (54, 59);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '스팸 / 도배', '잘못된 정보 포함', '처리완료', 95);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (55, 18);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '허위정보', '욕설 및 비방 포함', '처리완료', 58);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (56, 63);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '스팸 / 도배', '반복적인 광고 게시물', '허위신고', 83);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (57, 33);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '반복적인 광고 게시물', '허위신고', 24);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (58, 98);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '부적절한 내용', '욕설 및 비방 포함', '보류', 35);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (59, 73);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '허위정보', '기타 문제 신고', '처리완료', 44);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (60, 76);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '부적절한 내용', '기타 문제 신고', '허위신고', 90);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (61, 20);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '허위정보', '잘못된 정보 포함', '허위신고', 6);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (62, 41);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '잘못된 정보 포함', '보류', 17);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (63, 36);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '권리 침해', '기타 문제 신고', '처리완료', 14);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (64, 1);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '기타 문제 신고', '허위신고', 95);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (65, 46);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '허위정보', '잘못된 정보 포함', '처리완료', 59);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (66, 6);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '저작권 침해 신고', '보류', 51);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (67, 56);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '반복적인 광고 게시물', '처리완료', 35);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (68, 92);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '스팸 / 도배', '반복적인 광고 게시물', '처리중', 80);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (69, 27);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '스팸 / 도배', '반복적인 광고 게시물', '처리완료', 36);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (70, 86);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '허위정보', '반복적인 광고 게시물', '처리완료', 53);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (71, 56);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '기타 문제 신고', '보류', 56);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (72, 82);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '부적절한 내용', '욕설 및 비방 포함', '보류', 32);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (73, 90);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '권리 침해', '욕설 및 비방 포함', '처리중', 99);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (74, 88);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '부적절한 내용', '욕설 및 비방 포함', '처리완료', 98);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (75, 90);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '허위정보', '욕설 및 비방 포함', '처리중', 74);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (76, 60);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '부적절한 내용', '반복적인 광고 게시물', '처리중', 9);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (77, 36);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '허위정보', '반복적인 광고 게시물', '보류', 21);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (78, 86);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '반복적인 광고 게시물', '보류', 5);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (79, 70);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '허위정보', '욕설 및 비방 포함', '보류', 4);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (80, 66);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '허위정보', '반복적인 광고 게시물', '처리완료', 28);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (81, 90);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '권리 침해', '반복적인 광고 게시물', '처리중', 75);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (82, 97);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '반복적인 광고 게시물', '허위신고', 84);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (83, 96);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '저작권 침해 신고', '허위신고', 79);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (84, 92);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '스팸 / 도배', '저작권 침해 신고', '처리중', 85);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (85, 30);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '부적절한 내용', '기타 문제 신고', '보류', 1);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (86, 16);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '권리 침해', '기타 문제 신고', '허위신고', 54);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (87, 14);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '스팸 / 도배', '욕설 및 비방 포함', '처리완료', 53);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (88, 14);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '권리 침해', '욕설 및 비방 포함', '처리완료', 37);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (89, 66);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '기타 문제 신고', '보류', 12);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (90, 48);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '허위정보', '욕설 및 비방 포함', '처리중', 81);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (91, 46);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '부적절한 내용', '저작권 침해 신고', '처리완료', 36);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (92, 53);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '잘못된 정보 포함', '보류', 34);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (93, 10);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '반복적인 광고 게시물', '보류', 25);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (94, 79);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '저작권 침해 신고', '처리중', 77);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (95, 22);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '기타 문제 신고', '허위신고', 48);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (96, 92);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '권리 침해', '저작권 침해 신고', '보류', 88);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (97, 4);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '부적절한 내용', '반복적인 광고 게시물', '허위신고', 76);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (98, 28);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '기타', '잘못된 정보 포함', '처리중', 41);
INSERT INTO TBL_COMPANY_REPORT
(ID, COMPANY_ID)
VALUES (99, 70);

INSERT INTO TBL_REPORT
(ID, REPORT_TYPE, REPORT_DETAIL, REPORT_STATUS, MEMBER_ID)
VALUES (SEQ_REPORT.NEXTVAL, '스팸 / 도배', '저작권 침해 신고', '처리완료', 69);
INSERT INTO TBL_PROGRAM_REPORT
(ID, PROGRAM_ID)
VALUES (100, 6);